### ISSUE TITLE
Integers are read from (and written to) separate lines

### ISSUE THREAD

**Issue by shreevatsa** [zmbc/shakespearelang#5]
I wrote the following program:
```
A rose by any other name.
Romeo, a speaker.
Juliet, his muse.
           Act I: Something.
           Scene I: A garden.
[Enter Romeo and Juliet]
Romeo: Open your mind! Speak your mind!
Romeo: Listen to your heart! Open your heart!
Romeo: Open your mind! Speak your mind!
[Exeunt]
```
Then ran:
```
% echo "a1b\n2 c\nd" | shakespeare run echo.spl
```

What I expect will be printed: `a1b`. What actually happens:

```
% echo "a1b\n2 c\nd" | shakespeare run echo.spl

aTraceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/shakespeare", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/shakespearelang/cli.py", line 23, in run
    interpreter.run_play(play)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/shakespearelang/shakespeare_interpreter.py", line 212, in run_play
    done = self.step_forward(breakpoint_callback)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/shakespearelang/shakespeare_interpreter.py", line 196, in step_forward
    shouldnt_advance = self.run_event(event_to_run, breakpoint_callback)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/shakespearelang/shakespeare_interpreter.py", line 146, in run_event
    should_break = self.run_sentence(sentence, self._character_by_name(event.character))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/shakespearelang/shakespeare_interpreter.py", line 130, in run_sentence
    self._character_opposite(character).value = int(input())
ValueError: invalid literal for int() with base 10: '2 c'
```

(The "reference implementation" doesn't handle this correctly either.)

**Comment by zmbc** [comment]
Thanks for filing an issue!

You may already understand this, but just to be clear, the current behavior is that anything, whether an integer or a character, requires a newline after it in the input. The only difference between integer and character (and for no specific good reason) is that when the play asks for a character input, only the first character is paid attention to (i.e. if the input line is "a123foobar" the input received will be "a").

I decided to write it so that it requires newlines because this way I can use the idiomatic python `input` function, and it actually turns out to be more intuitive for interactive plays (i.e. when you're not piping input). I suspect the latter reason may also be the "problem" with the reference implementation.

Does that make sense? Is there an obvious design improvement I'm missing?

**Comment by shreevatsa** [comment]
Well, if one has input like `abc 123 def` on a line, one would expect to be able to read input character by character. The original implementation does this; for example from that line one can read 3 (or 4) characters `a`, `b`, `c`, and then the integer `123`. (The bug in that implementation is only that afterwards the rest of the line gets consumed, while I would expect that one can continue to read ` def`, character-by-character.)

With the implementation as here, there is literally no way to access characters after the first one... which makes it not very useful as a programming language. 

Of course, it is debatable whether Shakespeare really is useful as a programming language in the place :-)

**Comment by zmbc** [comment]
I see. Now that I think about it, that does make the most sense as a strategy.

Any interest in making a PR? If not, I'll look into it when I get some time.

**Comment by zmbc** [comment]
@shreevatsa I've made a first pass at the implementation of this. Let me know what you think.

Reading a character gets the next character without requiring it to be followed by a newline:
```
$ printf "a1b\n2 c\nd" | shakespeare run echo.spl
a1b
```

Reading a number reads as many consecutive digit characters as it finds:
```
$ printf "a123b\n2 c\nd" | shakespeare run echo.spl
a123b
```

Newline characters are read explicitly, like any other character:
```
$ printf "a123\n" | shakespeare run echo.spl
a123
       <-- note the trailing newline here
```

```
$ printf "\n123a" | shakespeare run echo.spl
      <-- output starts with newline
123
```
