### ISSUE TITLE
FailedParse exception when trying to use difference

### ISSUE THREAD

**Issue by erzoe** [zmbc/shakespearelang#9]
The following example causes an unexpected FailedParse exception:

```
The adventures of Romeo.

Romeo, the noble hero of our story.
Hamlet, a cursing man.

        Act I: Love and Hate.

        Scene I: Curses.

[Enter Hamlet and Romeo]

Hamlet:
  You are as normal as the sum of a smelly vile disgusting curse and a cowardly foul misused snotty evil misused leech. You are as tiny as the difference of a toad and yourself. Speak your mind!

[Exeunt]
```

The traceback is:

```
Traceback (most recent call last):
  File "~/.local/lib/python3.7/site-packages/grako/contexts.py", line 200, in parse
    result = rule()
  File "~/.local/lib/python3.7/site-packages/grako/contexts.py", line 48, in wrapper
    return self._call(rule, name, params, kwparams)
  File "~/.local/lib/python3.7/site-packages/grako/contexts.py", line 456, in _call
    node, newpos, newstate = self._invoke_rule(rule, name, params, kwparams)
  File "~/.local/lib/python3.7/site-packages/grako/contexts.py", line 496, in _invoke_rule
    rule(self)
  File "~/.local/lib/python3.7/site-packages/shakespearelang/shakespeare_parser.py", line 1689, in _play_
    self._check_eof()
  File "~/.local/lib/python3.7/site-packages/grako/contexts.py", line 636, in _check_eof
    self._error('Expecting end of text.')
  File "~/.local/lib/python3.7/site-packages/grako/contexts.py", line 431, in _error
    item
grako.exceptions.FailedParse: (13:121) Expecting end of text. :
  You are as normal as the sum of a smelly vile disgusting curse and a cowardly foul misused snotty evil misused leech. You are as tiny as the difference of a toad and yourself. Speak your mind!
                                                                                                                        ^
play

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.local/bin/shakespeare", line 10, in <module>
    sys.exit(main())
  File "~/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "~/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "~/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "~/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "~/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "~/.local/lib/python3.7/site-packages/shakespearelang/cli.py", line 26, in run
    interpreter.run_play(play)
  File "~/.local/lib/python3.7/site-packages/shakespearelang/shakespeare_interpreter.py", line 67, in run_play
    self.ast = self._parse_if_necessary(play, 'play')
  File "~/.local/lib/python3.7/site-packages/shakespearelang/shakespeare_interpreter.py", line 238, in _parse_if_necessary
    return self.parser.parse(item, rule_name=rule_name)
  File "~/.local/lib/python3.7/site-packages/grako/contexts.py", line 208, in parse
    raise self._furthest_exception
  File "~/.local/lib/python3.7/site-packages/grako/contexts.py", line 666, in _option
    yield
  File "~/.local/lib/python3.7/site-packages/shakespearelang/shakespeare_parser.py", line 1017, in block2
    self._negative_adjective_()
  File "~/.local/lib/python3.7/site-packages/grako/contexts.py", line 48, in wrapper
    return self._call(rule, name, params, kwparams)
  File "~/.local/lib/python3.7/site-packages/grako/contexts.py", line 456, in _call
    node, newpos, newstate = self._invoke_rule(rule, name, params, kwparams)
  File "~/.local/lib/python3.7/site-packages/grako/contexts.py", line 496, in _invoke_rule
    rule(self)
  File "~/.local/lib/python3.7/site-packages/shakespearelang/shakespeare_parser.py", line 305, in _negative_adjective_
    self._error('expecting one of: bad cowardly cursed damned dirty disgusting distasteful dusty evil fat fat-kidneyed fatherless foul hairy half-witted horrible horrid infected lying miserable misused oozing rotten smelly snotty sorry stinking stuffed stupid vile villainous worried')
  File "~/.local/lib/python3.7/site-packages/grako/contexts.py", line 431, in _error
    item
grako.exceptions.FailedParse: (13:144) expecting one of: bad cowardly cursed damned dirty disgusting distasteful dusty evil fat fat-kidneyed fatherless foul hairy half-witted horrible horrid infected lying miserable misused oozing rotten smelly snotty sorry stinking stuffed stupid vile villainous worried :
  You are as normal as the sum of a smelly vile disgusting curse and a cowardly foul misused snotty evil misused leech. You are as tiny as the difference of a toad and yourself. Speak your mind!
                                                                                                                                               ^
negative_adjective
negative_noun_phrase
noun_phrase
value
assignment
sentence
line
event
scene
act
play
```

When running this example with https://github.com/drsam94/Spl it gives the expected output `G`.

When I replace `difference` with `sum` I am not getting a FailedParse exception anymore (but a `ValueError: chr() arg not in range(0x110000)`).

When I replace what Romeo says with the following example from [Wikipedia](https://en.wikipedia.org/wiki/Shakespeare_(programming_language)#Example_code) it outputs the expected "e":
```
 You are as brave as the sum of your fat little stuffed misused dusty
 old rotten codpiece and a beautiful fair warm peaceful sunny summer's
 day. You are as healthy as the difference between the sum of the
 sweetest reddest rose and my father and yourself! Speak your mind!
```
Both example have a `sum` in the first sentence and a `difference` in the second sentence. I do not understand why the Wikipedia example works but mine does not.

**Comment by erzoe** [comment]
I have found my mistake: of course it needs to be `difference between` instead of `difference of`.
